#!/usr/bin/env python3
"""Build flat single-reference Anima Edit showcase from dual-ref ImagePulse layout.

Dual (source)::

    target/<stem>.png + .txt
    reference/<stem>/1.png, 2.png

Single (output)::

    target/<stem>.png + .txt
    reference/<stem>.png   # first separated image only
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _write_dataset_toml(dest: Path, dataset_toml: Path) -> None:
    rel_target = dest.relative_to(ROOT).as_posix()
    rel_ref = f"{rel_target}/reference"
    dataset_toml.write_text(
        f"""# Generated by script/ops/build_anima_edit_single_ref_showcase.py
[general]
caption_extension = ".txt"

[[datasets]]
resolution = [512, 512]
batch_size = 1
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[[datasets.subsets]]
image_dir = "./{rel_target}/target"
conditioning_data_dir = "./{rel_ref}"
""",
        encoding="utf-8",
    )


def build(
    src: Path,
    dest: Path,
    *,
    limit: int | None = None,
    stems: list[str] | None = None,
) -> list[dict]:
    src = src.resolve()
    dest = dest.resolve()
    target_src = src / "target"
    if not target_src.is_dir():
        raise SystemExit(f"Missing {target_src}")

    if stems:
        stem_list = list(stems)
    else:
        stem_list = sorted(p.stem for p in target_src.glob("*.txt"))
        if limit is not None:
            stem_list = stem_list[:limit]

    target_dst = dest / "target"
    ref_dst = dest / "reference"
    target_dst.mkdir(parents=True, exist_ok=True)
    ref_dst.mkdir(parents=True, exist_ok=True)

    manifest: list[dict] = []
    for stem in stem_list:
        caption = target_src / f"{stem}.txt"
        target_png = target_src / f"{stem}.png"
        ref1 = src / "reference" / stem / "1.png"
        if not caption.is_file() or not target_png.is_file():
            print(f"skip {stem}: missing target/caption")
            continue
        if not ref1.is_file():
            for alt in ("1.jpg", "1.webp"):
                candidate = src / "reference" / stem / alt
                if candidate.is_file():
                    ref1 = candidate
                    break
        if not ref1.is_file():
            print(f"skip {stem}: missing reference/{stem}/1.*")
            continue

        shutil.copy2(target_png, target_dst / target_png.name)
        shutil.copy2(caption, target_dst / caption.name)
        out_ref = ref_dst / f"{stem}{ref1.suffix.lower()}"
        shutil.copy2(ref1, out_ref)
        manifest.append(
            {
                "stem": stem,
                "target": f"target/{stem}.png",
                "reference": f"reference/{stem}{ref1.suffix.lower()}",
            }
        )

    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--src",
        type=Path,
        default=ROOT / "data" / "imagepulsev2-edit-merge-171",
        help="Dual-ref dataset root",
    )
    parser.add_argument(
        "--dest",
        type=Path,
        default=ROOT / "data" / "anima-edit-single-showcase",
    )
    parser.add_argument("--limit", type=int, default=32, help="Max samples (ignored if --stems set)")
    parser.add_argument(
        "--hero-stems",
        default="sample0000,sample0010,sample0020",
        help="Comma-separated stems for doc hero triptychs",
    )
    parser.add_argument(
        "--dataset-toml",
        type=Path,
        default=ROOT / "docs/examples/anima-edit-single-ref-dataset.toml",
    )
    args = parser.parse_args()

    dest = args.dest.resolve()
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    heroes = [s.strip() for s in args.hero_stems.split(",") if s.strip()]
    manifest = build(args.src, dest, limit=args.limit)
    if not manifest:
        raise SystemExit("No samples built.")

    hero_rows = [row for row in manifest if row["stem"] in heroes]
    (dest / "manifest.json").write_text(
        json.dumps(
            {
                "source": str(args.src.resolve()),
                "layout": "single reference: reference/<stem>.png -> target/<stem>.png",
                "count": len(manifest),
                "hero_stems": heroes,
                "heroes": hero_rows,
                "samples": manifest,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    _write_dataset_toml(dest, args.dataset_toml.resolve())
    print(f"built {len(manifest)} single-ref pairs -> {dest}")
    print(f"hero stems: {', '.join(heroes)}")
    print(f"dataset TOML: {args.dataset_toml.resolve()}")


if __name__ == "__main__":
    main()
