#!/usr/bin/env python3
"""Download a small MultiRef subset into anima-edit dual-reference layout.

Sources
-------
benchmark-real (default)
    ONE-Lab/MultiRef-benchmark, row_id < 1000, 3 images with parseable
    ``Edit image <imageN>`` prompt. Two non-canvas images -> reference/1,2;
    canvas image -> target/ (HF release has no separate Photoshop GT).

dataset
    ONE-Lab/MultiRef-dataset JSONL + parquet shards: 2x input_images + output_image
    (try-on, true supervised target). Streams parquet until all paths resolve.

Output layout::

    data/anima-edit-multiref-50/
      target/<stem>.png + <stem>.txt
      reference/<stem>/1.png, 2.png
      manifest.json
      README-data-limitation.md   (benchmark-real only)
"""

from __future__ import annotations

import argparse
import json
import random
import re
import shutil
from pathlib import Path

from huggingface_hub import hf_hub_download, list_repo_files

ROOT = Path(__file__).resolve().parents[2]
REPO_BENCHMARK = "ONE-Lab/MultiRef-benchmark"
REPO_DATASET = "ONE-Lab/MultiRef-dataset"
EDIT_IMAGE_RE = re.compile(r"Edit (?:the )?image <(image\d+)>", re.IGNORECASE)
IMG_TAG_RE = re.compile(r"<img>.*?</img>", re.IGNORECASE | re.DOTALL)
IMAGE_TOKEN_RE = re.compile(r"<\|image_\d+\|>")
IMAGE_REF_RE = re.compile(r"<image\d+>")


def _clean_caption(text: str) -> str:
    text = IMG_TAG_RE.sub(" ", text)
    text = IMAGE_TOKEN_RE.sub(" ", text)
    text = IMAGE_REF_RE.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip()


def _stem_from_row_id(row_id: int) -> str:
    return f"sample{row_id:04d}"


def _write_dataset_toml(out_root: Path, dataset_toml: Path | None) -> Path:
    rel_target = out_root.relative_to(ROOT).as_posix()
    rel_ref = f"{rel_target}/reference"
    content = f"""# Generated by script/ops/fetch_multiref_anima_edit_subset.py
[general]
caption_extension = ".txt"

[[datasets]]
resolution = [512, 512]
batch_size = 1
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[[datasets.subsets]]
image_dir = "./{rel_target}/target"
conditioning_data_dir = "./{rel_ref}"
conditioning_multi_reference = true
conditioning_reference_count = 2
"""
    path = dataset_toml or (ROOT / "docs/examples/anima-edit-multiref-dataset.toml")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def _benchmark_repo_paths() -> set[str]:
    return {
        path.replace("\\", "/")
        for path in list_repo_files(REPO_BENCHMARK, repo_type="dataset")
        if path.startswith("compressed_images/")
    }


def _select_benchmark_real(
    combined: list[dict],
    count: int,
    seed: int,
    *,
    available_paths: set[str] | None = None,
) -> list[dict]:
    selected: list[dict] = []
    for row in combined:
        if row.get("row_id", 10_000) >= 1000:
            continue
        mapping = row.get("image_path_mapping") or {}
        if len(mapping) != 3:
            continue
        match = EDIT_IMAGE_RE.search(row.get("prompt") or "")
        if not match:
            continue
        canvas_key = match.group(1)
        if canvas_key not in mapping:
            continue
        ref_keys = sorted(
            (k for k in mapping if k != canvas_key),
            key=lambda k: int(k[5:]),
        )
        if len(ref_keys) < 2:
            continue
        target_path = mapping[canvas_key]
        ref_paths = [mapping[ref_keys[0]], mapping[ref_keys[1]]]
        paths = [target_path, *ref_paths]
        if available_paths is not None and not all(p in available_paths for p in paths):
            continue
        selected.append(
            {
                "row_id": row["row_id"],
                "prompt": row["prompt"],
                "target_path": target_path,
                "ref_paths": ref_paths,
                "target_mode": "canvas",
            }
        )
    rng = random.Random(seed)
    rng.shuffle(selected)
    return selected[:count]


def _download_benchmark_files(samples: list[dict], out_root: Path) -> list[dict]:
    manifest: list[dict] = []
    target_dir = out_root / "target"
    target_dir.mkdir(parents=True, exist_ok=True)

    for item in samples:
        stem = _stem_from_row_id(item["row_id"])
        ref_dir = out_root / "reference" / stem
        ref_dir.mkdir(parents=True, exist_ok=True)

        target_src = item["target_path"]
        target_suffix = Path(target_src).suffix.lower() or ".jpg"
        target_dst = target_dir / f"{stem}{target_suffix}"
        hf_hub_download(
            REPO_BENCHMARK,
            target_src,
            repo_type="dataset",
            local_dir=str(out_root / "_hf_cache"),
        )
        cached = out_root / "_hf_cache" / target_src
        shutil.copy2(cached, target_dst)

        caption = _clean_caption(item["prompt"])
        (target_dir / f"{stem}.txt").write_text(caption, encoding="utf-8")

        ref_entries: list[str] = []
        for idx, ref_src in enumerate(item["ref_paths"], start=1):
            ref_suffix = Path(ref_src).suffix.lower() or ".jpg"
            ref_dst = ref_dir / f"{idx}{ref_suffix}"
            hf_hub_download(
                REPO_BENCHMARK,
                ref_src,
                repo_type="dataset",
                local_dir=str(out_root / "_hf_cache"),
            )
            shutil.copy2(out_root / "_hf_cache" / ref_src, ref_dst)
            ref_entries.append(ref_dst.relative_to(out_root).as_posix())

        manifest.append(
            {
                "row_id": item["row_id"],
                "stem": stem,
                "target": target_dst.relative_to(out_root).as_posix(),
                "references": ref_entries,
                "caption": caption,
                "target_mode": item["target_mode"],
            }
        )
    return manifest


def _select_dataset_jsonl(jsonl_path: Path, count: int, seed: int) -> list[dict]:
    rows: list[dict] = []
    with jsonl_path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            inputs = row.get("input_images") or []
            output = row.get("output_image")
            if len(inputs) == 2 and output:
                rows.append(row)
    rng = random.Random(seed)
    rng.shuffle(rows)
    picked: list[dict] = []
    for row in rows[:count]:
        inputs = row.get("input_images") or []
        output = row.get("output_image") or ""
        picked.append(
            {
                "instruction": row.get("instruction") or "",
                "target_path": "/" + str(output).lstrip("/"),
                "ref_paths": ["/" + str(p).lstrip("/") for p in inputs[:2]],
                "target_mode": "output_image",
            }
        )
    return picked


def _resolve_paths_from_parquet(
    needed: dict[str, list[tuple[str, str]]],
    out_root: Path,
    max_shards: int | None,
) -> None:
    try:
        import pyarrow.parquet as pq
    except ImportError as exc:
        raise SystemExit("pip install pyarrow (or datasets) for --source dataset") from exc

    shard_files = sorted(
        f
        for f in list_repo_files(REPO_DATASET, repo_type="dataset")
        if f.startswith("data/train-") and f.endswith(".parquet")
    )
    if max_shards is not None:
        shard_files = shard_files[:max_shards]

    remaining = sum(len(v) for v in needed.values())
    for shard_idx, shard_name in enumerate(shard_files):
        if remaining <= 0:
            break
        print(f"scan parquet {shard_idx + 1}/{len(shard_files)}: {shard_name} (remaining {remaining})")
        local = Path(
            hf_hub_download(REPO_DATASET, shard_name, repo_type="dataset")
        )
        table = pq.read_table(local, columns=["path", "image"])
        paths = table.column("path").to_pylist()
        images = table.column("image")
        for path_value, image_struct in zip(paths, images):
            norm = str(path_value).lstrip("/")
            pending = needed.get(norm)
            if not pending:
                continue
            image_bytes = image_struct["bytes"]
            for stem, role in pending:
                if role == "target":
                    suffix = Path(norm).suffix.lower() or ".jpg"
                    dst = out_root / "target" / f"{stem}{suffix}"
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    dst.write_bytes(image_bytes)
                else:
                    ref_idx = int(role)
                    suffix = Path(norm).suffix.lower() or ".jpg"
                    ref_dir = out_root / "reference" / stem
                    ref_dir.mkdir(parents=True, exist_ok=True)
                    (ref_dir / f"{ref_idx}{suffix}").write_bytes(image_bytes)
            del needed[norm]
            remaining = sum(len(v) for v in needed.values())

    if needed:
        missing = list(needed.keys())[:10]
        raise SystemExit(
            f"Could not resolve {len(needed)} paths from parquet "
            f"(showing first: {missing}). Try increasing --max-parquet-shards."
        )


def _materialize_dataset_source(
    samples: list[dict],
    out_root: Path,
    *,
    max_parquet_shards: int | None = None,
) -> list[dict]:
    target_dir = out_root / "target"
    target_dir.mkdir(parents=True, exist_ok=True)

    needed: dict[str, list[tuple[str, str]]] = {}
    meta: list[dict] = []

    for index, item in enumerate(samples):
        stem = f"sample{index:04d}"
        caption = _clean_caption(item["instruction"])
        (target_dir / f"{stem}.txt").write_text(caption, encoding="utf-8")
        needed.setdefault(item["target_path"].lstrip("/"), []).append((stem, "target"))
        needed.setdefault(item["ref_paths"][0].lstrip("/"), []).append((stem, "1"))
        needed.setdefault(item["ref_paths"][1].lstrip("/"), []).append((stem, "2"))
        meta.append(
            {
                "stem": stem,
                "caption": caption,
                "target_mode": item["target_mode"],
                "target_path": item["target_path"],
                "ref_paths": item["ref_paths"],
            }
        )

    _resolve_paths_from_parquet(needed, out_root, max_shards=max_parquet_shards)
    manifest: list[dict] = []
    for item in meta:
        stem = item["stem"]
        target_file = next(target_dir.glob(f"{stem}.*"))
        ref_dir = out_root / "reference" / stem
        refs = sorted(ref_dir.glob("*"))
        manifest.append(
            {
                "stem": stem,
                "target": target_file.relative_to(out_root).as_posix(),
                "references": [p.relative_to(out_root).as_posix() for p in refs],
                "caption": item["caption"],
                "target_mode": item["target_mode"],
            }
        )
    return manifest


def _write_limitation_readme(out_root: Path) -> None:
    text = """# MultiRef benchmark-real subset — data limitation

This folder was built from `ONE-Lab/MultiRef-benchmark` (real_world, row_id < 1000).

The Hugging Face release includes **input images and prompts only**, not the separate
Photoshop **ground-truth result** images described in the paper. For pipeline smoke tests
we map:

- `reference/1.png`, `reference/2.png` — the two non-canvas reference images from the prompt
- `target/` — the **canvas** image (`Edit image <imageN>`), **not** the edited output

Use this layout to validate dual-reference **loading, latent caching, and training loops**.
For supervised edit quality, prefer `--source dataset` (MultiRef-dataset with `output_image`).

See `docs/anima-training.md` — 外部数据集选型.
"""
    (out_root / "README-data-limitation.md").write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--count",
        type=int,
        default=48,
        help="Number of samples (default 48; benchmark-real has 48 complete triplets on HF)",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--source",
        choices=("benchmark-real", "dataset"),
        default="benchmark-real",
        help="benchmark-real: Reddit real_world; dataset: try-on with true GT",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output root (default data/anima-edit-multiref-<count>)",
    )
    parser.add_argument(
        "--dataset-toml",
        type=Path,
        default=None,
        help="Write dataset TOML (default docs/examples/anima-edit-multiref-dataset.toml)",
    )
    parser.add_argument(
        "--max-parquet-shards",
        type=int,
        default=None,
        help="dataset source only: limit parquet shards scanned (debug)",
    )
    args = parser.parse_args()

    out_root = (args.out or (ROOT / f"data/anima-edit-multiref-{args.count}")).resolve()
    if out_root.exists():
        shutil.rmtree(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    if args.source == "benchmark-real":
        combined_path = Path(
            hf_hub_download(REPO_BENCHMARK, "combined1990.json", repo_type="dataset")
        )
        combined = json.loads(combined_path.read_text(encoding="utf-8"))
        print("listing benchmark image paths...")
        available_paths = _benchmark_repo_paths()
        samples = _select_benchmark_real(
            combined,
            args.count,
            args.seed,
            available_paths=available_paths,
        )
        if len(samples) < args.count:
            raise SystemExit(
                f"Only {len(samples)} benchmark-real triplets with all files on HF "
                f"(requested {args.count})."
            )
        manifest = _download_benchmark_files(samples, out_root)
        _write_limitation_readme(out_root)
    else:
        jsonl_path = Path(
            hf_hub_download(REPO_DATASET, "new_training_data.jsonl", repo_type="dataset")
        )
        samples = _select_dataset_jsonl(jsonl_path, args.count, args.seed)
        manifest = _materialize_dataset_source(
            samples, out_root, max_parquet_shards=args.max_parquet_shards
        )

    (out_root / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    toml_path = _write_dataset_toml(out_root, args.dataset_toml)

    cache_dir = out_root / "_hf_cache"
    if cache_dir.exists():
        shutil.rmtree(cache_dir)

    print(f"source: {args.source}")
    print(f"output: {out_root}")
    print(f"samples: {len(manifest)}")
    print(f"dataset TOML: {toml_path}")
    if args.source == "benchmark-real":
        print(
            "NOTE: target/ holds the edit CANVAS (no PS GT on HF). "
            "See README-data-limitation.md"
        )


if __name__ == "__main__":
    main()
