#!/usr/bin/env python3
"""Build dual-ref sample-prompts.toml from data/anima-edit-showcase-dual-curated/manifest.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _toml_escape(value: str) -> str:
    if "\n" in value or '"' in value:
        return '"""' + value.replace('"""', '\\"""') + '"""'
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=ROOT / "data" / "anima-edit-showcase-dual-curated",
    )
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--width", type=int, default=512)
    parser.add_argument("--height", type=int, default=512)
    args = parser.parse_args()

    root = args.root.resolve()
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    cases = manifest.get("cases") or []
    if not cases:
        raise SystemExit("No cases in manifest.json")

    lines = [
        "# Generated by script/ops/generate_anima_edit_showcase_dual_prompts.py",
        "",
    ]
    negative = "low quality, blurry, noisy, bad anatomy, deformed"

    for case in cases:
        case_id = case["id"]
        ref_dir = ROOT / case["reference_dir"]
        cap_path = ROOT / case["caption_file"]
        prompt = cap_path.read_text(encoding="utf-8").strip()
        ref_rel = Path("../../") / ref_dir.relative_to(ROOT).as_posix()
        count = int(case.get("reference_count", 2))
        lines.extend(
            [
                "[[prompts]]",
                f"prompt = {_toml_escape(prompt)}",
                f"negative_prompt = {_toml_escape(negative)}",
                f"width = {args.width}",
                f"height = {args.height}",
                "scale = 4.5",
                "seed = 42",
                "sample_steps = 50",
                "flow_shift = 3.0",
                f'reference_dir = "{ref_rel.as_posix()}"',
                f"reference_count = {count}",
                "",
            ]
        )

    args.out.resolve().write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(cases)} dual prompt(s) -> {args.out}")


if __name__ == "__main__":
    main()
