#!/usr/bin/env python3
"""Generate anima-edit sample-prompts.toml from imported dataset (target/*.txt captions)."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _toml_escape(value: str) -> str:
    if "\n" in value or '"' in value:
        return '"""' + value.replace('"""', '\\"""') + '"""'
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=ROOT / "data" / "imagepulsev2-edit-merge-171",
        help="Imported dataset root (target/ + reference/)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output TOML path (e.g. docs/examples/...-sample-prompts.toml)",
    )
    parser.add_argument("--stems", nargs="*", default=None, help="Stems to include (default: first only)")
    parser.add_argument("--width", type=int, default=512)
    parser.add_argument("--height", type=int, default=512)
    parser.add_argument("--scale", type=float, default=4.5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--sample-steps", type=int, default=50)
    parser.add_argument("--flow-shift", type=float, default=3.0)
    args = parser.parse_args()

    data_dir = args.data_dir.resolve()
    target_dir = data_dir / "target"
    if not target_dir.is_dir():
        raise SystemExit(f"Missing target dir: {target_dir}")

    stems = args.stems
    if not stems:
        txts = sorted(target_dir.glob("*.txt"))
        if not txts:
            raise SystemExit(f"No captions in {target_dir}")
        stems = [txts[0].stem]

    out_path = args.out.resolve()
    rel_data = Path("../../") / data_dir.relative_to(ROOT).as_posix()
    ref_root = data_dir / "reference"

    lines = [
        "# Generated by script/ops/generate_anima_edit_sample_prompts.py",
        f"# data_dir={data_dir.relative_to(ROOT).as_posix()}",
        "# Preview uses the same caption as training (target/<stem>.txt).",
        "",
    ]
    negative = "low quality, blurry, noisy, bad anatomy, deformed"

    for stem in stems:
        caption_path = target_dir / f"{stem}.txt"
        if not caption_path.is_file():
            raise SystemExit(f"Missing caption: {caption_path}")
        prompt = caption_path.read_text(encoding="utf-8").strip()
        ref_block: list[str]
        flat_ref = None
        for ext in (".png", ".jpg", ".jpeg", ".webp"):
            candidate = ref_root / f"{stem}{ext}"
            if candidate.is_file():
                flat_ref = candidate
                break
        if flat_ref is not None:
            ref_rel = (rel_data / "reference" / flat_ref.name).as_posix()
            ref_block = [f'references = ["{ref_rel}"]']
        else:
            ref_dir = (rel_data / "reference" / stem).as_posix()
            ref_block = [f'reference_dir = "{ref_dir}"', "reference_count = 2"]
        lines.extend(
            [
                "[[prompts]]",
                f"prompt = {_toml_escape(prompt)}",
                f"negative_prompt = {_toml_escape(negative)}",
                f"width = {args.width}",
                f"height = {args.height}",
                f"scale = {args.scale}",
                f"seed = {args.seed}",
                f"sample_steps = {args.sample_steps}",
                f"flow_shift = {args.flow_shift}",
                *ref_block,
                "",
            ]
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(stems)} prompt(s) -> {out_path}")


if __name__ == "__main__":
    main()
