#!/usr/bin/env python3
"""Import ImagePulseV2 expression-edit shard (tar.gz or flat dir) into single-ref layout.

Source JSON fields::

    image          # reference (before)
    image_edited   # target (after)
    edit_prompt    # target expression description (zh)
    generated_edit_prompt  # forward edit instruction (zh)
    generated_reversed_edit_prompt  # reverse edit (en)

Output::

    data/imagepulsev2-expression/
      target/<stem>.png + <stem>.txt
      reference/<stem>.png
      manifest.json
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
import tarfile
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    Image = None  # type: ignore[misc, assignment]

ROOT = Path(__file__).resolve().parents[2]
CAPTION_FIELDS = (
    "generated_edit_prompt",
    "edit_prompt",
    "generated_reversed_edit_prompt",
)


def _write_dataset_toml(out_root: Path, dataset_toml: Path) -> None:
    rel_target = out_root.relative_to(ROOT).as_posix()
    rel_ref = f"{rel_target}/reference"
    dataset_toml.write_text(
        f"""# Generated by script/ops/import_imagepulsev2_expression_local.py
[general]
caption_extension = ".txt"

[[datasets]]
resolution = [512, 512]
batch_size = 1
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[[datasets.subsets]]
image_dir = "./{rel_target}/target"
conditioning_data_dir = "./{rel_ref}"
""",
        encoding="utf-8",
    )


def _is_valid_image(path: Path) -> bool:
    if not path.is_file() or path.stat().st_size < 64:
        return False
    if Image is None:
        return True
    try:
        with Image.open(path) as image:
            image.verify()
        return True
    except Exception:
        return False


def _pick_caption(meta: dict, field: str) -> str:
    if field != "auto":
        value = (meta.get(field) or "").strip()
        if value:
            return value
    for key in CAPTION_FIELDS:
        value = (meta.get(key) or "").strip()
        if value:
            return value
    return "Adjust the character facial expression as described, keep identity and outfit unchanged."


def _iter_json_members(src: Path):
    if src.is_file() and src.suffixes[-2:] == [".tar", ".gz"] or str(src).endswith(".tar.gz"):
        with tarfile.open(src, "r:gz") as tf:
            prefix = None
            for name in tf.getnames():
                if name.endswith(".json"):
                    parts = name.split("/")
                    if len(parts) >= 2 and not prefix:
                        prefix = parts[0] + "/"
                    yield tf, name, prefix
        return
    if not src.is_dir():
        raise SystemExit(f"Source not found: {src}")
    for json_path in sorted(src.glob("*.json")):
        yield None, str(json_path), None


def import_shard(
    src: Path,
    dest: Path,
    *,
    limit: int | None = None,
    seed: int = 42,
    shuffle: bool = False,
    caption_field: str = "generated_edit_prompt",
) -> list[dict]:
    dest = dest.resolve()
    target_dir = dest / "target"
    ref_dir = dest / "reference"
    target_dir.mkdir(parents=True, exist_ok=True)
    ref_dir.mkdir(parents=True, exist_ok=True)

    entries: list[tuple[str, dict, tarfile.TarFile | None]] = []
    tar_handle: tarfile.TarFile | None = None
    if src.is_file() and str(src).endswith(".tar.gz"):
        tar_handle = tarfile.open(src, "r:gz")
        prefix = ""
        for name in tar_handle.getnames():
            if not name.endswith(".json"):
                continue
            parts = Path(name).parts
            if len(parts) >= 2:
                prefix = parts[0] + "/"
                break
        for name in sorted(tar_handle.getnames()):
            if not name.endswith(".json"):
                continue
            meta = json.loads(tar_handle.extractfile(name).read().decode("utf-8"))
            entries.append((prefix, meta, tar_handle))
    else:
        src = src.resolve()
        if not src.is_dir():
            raise SystemExit(f"Source directory not found: {src}")
        for json_path in sorted(src.glob("*.json")):
            meta = json.loads(json_path.read_text(encoding="utf-8"))
            entries.append(("", meta, None))

    if shuffle:
        rng = random.Random(seed)
        rng.shuffle(entries)

    manifest: list[dict] = []
    try:
        for prefix, meta, tf in entries:
            if limit is not None and len(manifest) >= limit:
                break
            ref_name = meta.get("image")
            tgt_name = meta.get("image_edited")
            if not ref_name or not tgt_name:
                continue

            if tf is not None:
                ref_member = f"{prefix}{ref_name}" if prefix else ref_name
                tgt_member = f"{prefix}{tgt_name}" if prefix else tgt_name
                ref_src_data = tf.extractfile(ref_member)
                tgt_src_data = tf.extractfile(tgt_member)
                if ref_src_data is None or tgt_src_data is None:
                    print(f"skip: missing png for {ref_name}")
                    continue
                ref_bytes = ref_src_data.read()
                tgt_bytes = tgt_src_data.read()
            else:
                src_dir = src if src.is_dir() else src.parent
                ref_path = src_dir / ref_name
                tgt_path = src_dir / tgt_name
                if not _is_valid_image(ref_path) or not _is_valid_image(tgt_path):
                    print(f"skip: invalid images {ref_name}")
                    continue
                ref_bytes = ref_path.read_bytes()
                tgt_bytes = tgt_path.read_bytes()

            stem = f"expr{len(manifest):04d}"
            ref_dst = ref_dir / f"{stem}.png"
            tgt_dst = target_dir / f"{stem}.png"
            ref_dst.write_bytes(ref_bytes)
            tgt_dst.write_bytes(tgt_bytes)
            if not _is_valid_image(ref_dst) or not _is_valid_image(tgt_dst):
                ref_dst.unlink(missing_ok=True)
                tgt_dst.unlink(missing_ok=True)
                print(f"skip {stem}: invalid written images")
                continue

            caption = _pick_caption(meta, caption_field)
            (target_dir / f"{stem}.txt").write_text(caption, encoding="utf-8")
            manifest.append(
                {
                    "stem": stem,
                    "reference": f"reference/{stem}.png",
                    "target": f"target/{stem}.png",
                    "caption_field": caption_field,
                    "source_image": ref_name,
                    "source_edited": tgt_name,
                }
            )
    finally:
        if tar_handle is not None:
            tar_handle.close()

    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--src",
        type=Path,
        required=True,
        help="Path to .tar.gz or extracted flat directory",
    )
    parser.add_argument(
        "--dest",
        type=Path,
        default=ROOT / "data" / "imagepulsev2-expression",
    )
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--shuffle", action="store_true")
    parser.add_argument(
        "--caption-field",
        default="generated_edit_prompt",
        choices=("generated_edit_prompt", "edit_prompt", "generated_reversed_edit_prompt", "auto"),
    )
    parser.add_argument(
        "--dataset-toml",
        type=Path,
        default=ROOT / "docs" / "examples" / "anima-edit-expression-dataset.toml",
    )
    args = parser.parse_args()

    if args.dest.exists():
        shutil.rmtree(args.dest)
    args.dest.mkdir(parents=True, exist_ok=True)

    manifest = import_shard(
        args.src,
        args.dest,
        limit=args.limit,
        seed=args.seed,
        shuffle=args.shuffle,
        caption_field=args.caption_field,
    )
    (args.dest / "manifest.json").write_text(
        json.dumps({"count": len(manifest), "samples": manifest}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    _write_dataset_toml(args.dest, args.dataset_toml)
    print(f"imported {len(manifest)} pairs -> {args.dest.relative_to(ROOT).as_posix()}")
    print(f"dataset toml -> {args.dataset_toml.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
