#!/usr/bin/env python3
"""Import local ImagePulseV2-Edit-Merge shard into anima-edit dual-reference layout.

Source layout (flat directory)::

    <src>/
      1775728130650974531.json
      1775728130650974531.png          # mergedimage (target)
      1775728131057301503.png          # seperated image refs
      ...

Output::

    data/imagepulsev2-edit-merge-171/
      target/sample0000.png + sample0000.txt
      reference/sample0000/1.png, 2.png
      manifest.json
"""

from __future__ import annotations

import argparse
import json
import random
import re
import shutil
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    Image = None  # type: ignore[misc, assignment]

ROOT = Path(__file__).resolve().parents[2]
SEP_KEYS = ("seperated image", "separated image")


def _write_dataset_toml(out_root: Path, dataset_toml: Path) -> None:
    rel_target = out_root.relative_to(ROOT).as_posix()
    rel_ref = f"{rel_target}/reference"
    dataset_toml.write_text(
        f"""# Generated by script/ops/import_imagepulsev2_local.py
[general]
caption_extension = ".txt"

[[datasets]]
resolution = [512, 512]
batch_size = 1
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[[datasets.subsets]]
image_dir = "./{rel_target}/target"
conditioning_data_dir = "./{rel_ref}"
conditioning_multi_reference = true
conditioning_reference_count = 2
""",
        encoding="utf-8",
    )


def _is_valid_image(path: Path) -> bool:
    if not path.is_file() or path.stat().st_size < 64:
        return False
    if Image is None:
        return True
    try:
        with Image.open(path) as image:
            image.verify()
        return True
    except Exception:
        return False


def _separated_images(meta: dict) -> list[str]:
    for key in SEP_KEYS:
        value = meta.get(key)
        if isinstance(value, list) and value:
            return [str(name) for name in value]
    return []


def import_shard(
    src: Path,
    dest: Path,
    *,
    limit: int | None = None,
    seed: int = 42,
    caption_lang: str = "en",
    shuffle: bool = False,
    caption_regex: str | None = None,
) -> list[dict]:
    src = src.resolve()
    dest = dest.resolve()
    if not src.is_dir():
        raise SystemExit(f"Source directory not found: {src}")

    json_files = sorted(src.glob("*.json"))
    if caption_regex:
        caption_re = re.compile(caption_regex, re.IGNORECASE)
        filtered: list[Path] = []
        for json_path in json_files:
            meta = json.loads(json_path.read_text(encoding="utf-8"))
            caption_probe = " ".join(
                str(meta.get(key) or "")
                for key in ("edit_prompt_en", "edit_prompt_zh", "edit_prompt")
            )
            if caption_re.search(caption_probe):
                filtered.append(json_path)
        json_files = filtered
    if shuffle:
        rng = random.Random(seed)
        json_files = list(json_files)
        rng.shuffle(json_files)
    if limit is not None:
        json_files = json_files[:limit]

    target_dir = dest / "target"
    target_dir.mkdir(parents=True, exist_ok=True)
    manifest: list[dict] = []

    for index, json_path in enumerate(json_files):
        meta = json.loads(json_path.read_text(encoding="utf-8"))
        merged = meta.get("mergedimage") or meta.get("merged_image") or []
        separated = _separated_images(meta)
        if not merged or len(separated) < 2:
            print(f"skip {json_path.name}: need mergedimage + 2 separated images")
            continue

        stem = f"sample{len(manifest):04d}"
        ref_dir = dest / "reference" / stem
        ref_dir.mkdir(parents=True, exist_ok=True)

        merged_name = merged[0]
        merged_src = src / merged_name
        if not merged_src.is_file():
            print(f"skip {json_path.name}: missing merged file {merged_name}")
            continue
        if not _is_valid_image(merged_src):
            print(f"skip {json_path.name}: invalid or empty merged file {merged_name}")
            continue

        target_suffix = merged_src.suffix.lower() or ".png"
        target_dst = target_dir / f"{stem}{target_suffix}"
        shutil.copy2(merged_src, target_dst)

        if caption_lang == "zh":
            caption = (meta.get("edit_prompt_zh") or meta.get("edit_prompt_en") or "").strip()
        else:
            caption = (meta.get("edit_prompt_en") or meta.get("edit_prompt_zh") or "").strip()
        if not caption:
            caption = "image edit"
        (target_dir / f"{stem}.txt").write_text(caption, encoding="utf-8")

        ref_entries: list[str] = []
        for ref_idx, ref_name in enumerate(separated[:2], start=1):
            ref_src = src / ref_name
            if not ref_src.is_file():
                print(f"skip {json_path.name}: missing reference file {ref_name}")
                ref_entries = []
                break
            if not _is_valid_image(ref_src):
                print(f"skip {json_path.name}: invalid reference file {ref_name}")
                ref_entries = []
                break
            ref_suffix = ref_src.suffix.lower() or ".png"
            ref_dst = ref_dir / f"{ref_idx}{ref_suffix}"
            shutil.copy2(ref_src, ref_dst)
            ref_entries.append(ref_dst.relative_to(dest).as_posix())

        if len(ref_entries) < 2:
            if target_dst.exists():
                target_dst.unlink()
            if ref_dir.exists():
                shutil.rmtree(ref_dir)
            (target_dir / f"{stem}.txt").unlink(missing_ok=True)
            continue

        manifest.append(
            {
                "stem": stem,
                "source_json": json_path.name,
                "target": target_dst.relative_to(dest).as_posix(),
                "references": ref_entries,
                "separated_count": len(separated),
                "caption_lang": caption_lang,
            }
        )

    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--src",
        type=Path,
        required=True,
        help="Flat directory with JSON + PNG (extracted tar contents)",
    )
    parser.add_argument(
        "--dest",
        type=Path,
        default=ROOT / "data" / "imagepulsev2-edit-merge-171",
        help="Output root under data/",
    )
    parser.add_argument("--limit", type=int, default=None, help="Max samples to import")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--shuffle", action="store_true")
    parser.add_argument(
        "--caption-lang",
        choices=("en", "zh"),
        default="en",
        help="Caption field for target/*.txt (default: en)",
    )
    parser.add_argument(
        "--caption-regex",
        default=None,
        help="Only import rows whose edit_prompt matches this regex (e.g. style|画风)",
    )
    parser.add_argument(
        "--dataset-toml",
        type=Path,
        default=ROOT / "docs/examples/anima-edit-imagepulse-dataset.toml",
    )
    args = parser.parse_args()

    dest = args.dest.resolve()
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    manifest = import_shard(
        args.src,
        dest,
        limit=args.limit,
        seed=args.seed,
        caption_lang=args.caption_lang,
        shuffle=args.shuffle,
        caption_regex=args.caption_regex,
    )
    if not manifest:
        raise SystemExit("No samples imported.")

    (dest / "manifest.json").write_text(
        json.dumps(
            {
                "source": str(args.src.resolve()),
                "dataset": "ImagePulseV2-Edit-Merge (local shard)",
                "count": len(manifest),
                "layout": "mergedimage -> target/, seperated image[:2] -> reference/",
                "samples": manifest,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    _write_dataset_toml(dest, args.dataset_toml.resolve())

    triple_ref = sum(1 for row in manifest if row.get("separated_count", 2) > 2)
    print(f"imported: {len(manifest)} samples -> {dest}")
    print(f"dataset TOML: {args.dataset_toml.resolve()}")
    if triple_ref:
        print(f"note: {triple_ref} source rows had 3 separated images; used first 2 as references.")


if __name__ == "__main__":
    main()
